/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\scene.gltf 
Author: Javier Martín Hidalgo (https://sketchfab.com/Jj.Mmhh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laser-saber-sith-52791ba8eb284a8b9b36c6ca52ae201b
Title: Laser Saber sith
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.077, 85.336, 13.116]}>
        <mesh geometry={nodes.sable_laser_negro_0.geometry} material={materials.negro} />
        <mesh geometry={nodes.sable_laser_plateado_0.geometry} material={materials.plateado} />
        <mesh geometry={nodes.sable_laser_luz_0.geometry} material={materials.material} />
        <mesh geometry={nodes.sable_laser_emision_0.geometry} material={materials.emision} />
        <mesh geometry={nodes.sable_laser_detalles_mango_0.geometry} material={materials.detalles_mango} />
        <mesh geometry={nodes.sable_laser_cuadrado_0.geometry} material={materials.cuadrado} />
        <mesh geometry={nodes.sable_laser_botones_0.geometry} material={materials.botones} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
