/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\scene.gltf 
Author: Rowan Design (https://sketchfab.com/rowansreid)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beat-saber-ideas-d2a0c0f248564ce086db6bd016a190a3
Title: Beat Saber Ideas
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SaberShape(props) {
  const { nodes, materials } = useGLTF('/laser_saber_sith/scene.gltf')
  return (
    <group {...props} dispose={null} >
      <group position={[1.7,-5,5.3]} rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh geometry={nodes.sable_laser_negro_0.geometry} material={materials.negro} />
        <mesh geometry={nodes.sable_laser_plateado_0.geometry} material={materials.plateado} />
        <mesh geometry={nodes.sable_laser_luz_0.geometry} material={materials.material} />
        <mesh geometry={nodes.sable_laser_emision_0.geometry} material={materials.emision} />
        <mesh geometry={nodes.sable_laser_detalles_mango_0.geometry} material={materials.detalles_mango} />
        <mesh geometry={nodes.sable_laser_cuadrado_0.geometry} material={materials.cuadrado} />
        <mesh geometry={nodes.sable_laser_botones_0.geometry} material={materials.botones} />
      </group>
    </group>
  )
}

useGLTF.preload('/beat_saber_ideas/scene.gltf')
